<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="middle_box" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="x_length" value="0.5"/>
    <xacro:property name="y_length" value="0.5" /> <!-- arbitrary value for mass -->
    <xacro:property name="z_length" value="0.4" /> <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="mass" value="25" /> <!-- arbitrary value for mass -->
    
    <xacro:include filename="$(find mobile_manipulator_description)/urdf/box_materials.xacro" />
    
    <!-- Used for fixing robot to Gazebo 'base_link' -->
    
    

    <link name="box">
        <collision>
            <origin xyz="0 0 ${z_length/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${x_length} ${y_length} ${z_length}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 -0.285" rpy="0 0 0"/>
            <geometry>
                <mesh scale="0.001 0.001 0.001" filename="package://mobile_manipulator_description/meshes/box.stl" />
            </geometry>
            <material name="white"/>
        </visual>

        <intertial>
            <origin xyz="0 0 ${z_length/2}" rpy="0 0 0"/>
            <mass value="${mass}"/>
            <inertia
                ixx="${mass / 12.0 * (y_length*y_length+z_length*z_length)}" ixy="0.0" ixz="0.0"
                iyy="${mass / 12.0 * (z_length*z_length+x_length*x_length)}" iyz="0.0"
                izz="${mass / 12.0 * (x_length*x_length+y_length*y_length)}"/>
        </intertial>
    </link>

    <joint name="box-base_link" type="fixed">
        <parent link="base_link"/>
        <child link="box"/>
        <origin xyz="0 0 0.02" rpy="0 0 0"/>
    </joint>
    
</robot>